spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db-db-equipment?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

springdoc.swagger-ui.path=/swagger-ui.html
spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
keycloak.url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.realm=Fpl-ferme-management
management.endpoint.prometheus.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
